---
- name: Download repo
  get_url:
    url: "{{ gitrepo_url }}"
    dest: "{{ gitrepo_install_path }}/repo"

- name: Set file attributes on repo
  file: path={{ gitrepo_install_path }}/repo mode=0755
